version: '3.3'
services:
  mysql:
    env_file:
    - site.env
    image: ${MYSQL_IMAGE}
    restart: always
    volumes:
      - mysql_v:/var/lib/mysql
  adminer:
    env_file:
    - site.env
    depends_on:
     - mysql
    image: ${ADMINER_IMAGE}
    restart: always
    ports:
      - 8081:8080
  wordpress:
    env_file:
    - site.env
    depends_on:
     - mysql
    image: ${WP_IMAGE}
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress_v:/var/www/html
volumes:
  mysql_v:
  wordpress_v:
