export SYSYEMD_DIR=/etc/systemd/system
export HOST_ROOT='/srv/production'

export NGINX_PROXY_NAME="nginx_proxy"
export NGINX_PROXY_VERSION="1"
export NGINX_PROXY_ROOT=$HOST_ROOT/$NGINX_PROXY_NAME/${NGINX_PROXY_VERSION}

export NGINX_GEN_NAME="nginx_gen"
export NGINX_GEN_VERSION="0"
export NGINX_GEN_ROOT=$HOST_ROOT/$NGINX_GEN_NAME/${NGINX_GEN_VERSION}

export NGINX_LENTENCRYPT_NAME="nginx_letsencrypt"
export NGINX_LENTENCRYPT_VERSION="1"
