export NGINX_PROXY_VERSION="1"
export NGINX_PROXY_NAME="nginx_proxy_${NGINX_PROXY_VERSION}"
export NGINX_PROXY_ROOT="$HOST_ROOT/$NGINX_PROXY_NAME"

export NGINX_GEN_VERSION="0"
export NGINX_GEN_NAME="nginx_gen_${NGINX_GEN_VERSION}"
export NGINX_GEN_ROOT="$HOST_ROOT/$NGINX_GEN_NAME"
export NGINX_LENTENCRYPT_VERSION="1"
export NGINX_LENTENCRYPT_NAME="nginx_letsencrypt_${NGINX_LENTENCRYPT_VERSION}"
